# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='endereço',
            field=models.CharField(default='vazio', max_length=200),
            preserve_default=False,
        ),
    ]
