# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contato_endereço'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
