# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
