# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171116_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='nome',
            field=models.CharField(default='vazio', max_length=200),
            preserve_default=False,
        ),
    ]
